# Generated by Django 5.2.3 on 2025-06-27 02:12

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(help_text="A unique code for the environment within this vendor (e.g., 'prod', 'dev').")),
                ('target_url', models.URLField(help_text='The full URL to forward requests to.', max_length=512)),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default environment for the vendor? Only one can be default.')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(help_text='A unique, URL-safe identifier for the vendor.', unique=True)),
                ('secure_variables', encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Encrypted JSON object of secure variables (e.g., API keys).', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(help_text="The sender's WhatsApp ID (phone number).", max_length=20)),
                ('name', models.CharField(help_text='A descriptive name for this rule.', max_length=100)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='router.environment')),
            ],
        ),
        migrations.AddField(
            model_name='environment',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='router.vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='environment',
            unique_together={('vendor', 'code')},
        ),
    ]
