# Generated by Django 5.2.3 on 2025-07-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('vendor_code', models.CharField(max_length=50)),
                ('wa_id', models.CharField(max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['meta_id'], name='router_proc_meta_id_2dfc11_idx'), models.Index(fields=['processed_at'], name='router_proc_process_97133a_idx')],
            },
        ),
    ]
